import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateReport = (project) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // -- Header --
    // Logo Placeholder
    doc.setFillColor(37, 99, 235); // Primary Blue
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text("AuditX Evaluation Report", pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text("Official Academic Project Assessment", pageWidth / 2, 30, { align: 'center' });

    // -- Project Details --
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Project Details", 14, 55);

    const details = [
        ["Project Title", project.title],
        ["Team Name", project.teamName],
        ["Team Leader", project.leaderName],
        ["Course", `${project.courseCode || 'N/A'} - ${project.subjectName || 'N/A'}`],
        ["Semester / Year", `${project.semester || 'N/A'} / ${project.academicYear || 'N/A'}`],
        ["Domain", project.domain],
        ["Tech Stack", project.techStack]
    ];

    doc.autoTable({
        startY: 60,
        head: [],
        body: details,
        theme: 'plain',
        styles: { fontSize: 11, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
    });

    // -- Evaluation Rubric --
    doc.text("Performance Assessment", 14, doc.lastAutoTable.finalY + 15);

    if (project.evaluation) {
        const rubric = [
            ["Code Quality", `${project.evaluation.marks.codeQuality} / 20`, "Structure, readability, handling limits"],
            ["Logic & Implementation", `${project.evaluation.marks.logic} / 20`, "Correctness, algorithms, execution"],
            ["Architecture & Design", `${project.evaluation.marks.architecture} / 15`, "Modularity, patterns, scalability"],
            ["Innovation", `${project.evaluation.marks.innovation} / 20`, "Uniqueness, creativity, problem solving"],
            ["Viva Voce", `${project.evaluation.marks.viva} / 25`, "Communication, technical depth, QA"],
            [{ content: "Total Score", styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } }, { content: `${project.evaluation.total} / 100`, styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } }, { content: project.evaluation.total >= 70 ? "Distinction" : project.evaluation.total >= 40 ? "Pass" : "Re-appear", styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } }]
        ];

        doc.autoTable({
            startY: doc.lastAutoTable.finalY + 20,
            head: [['Criteria', 'Score', 'Remarks']],
            body: rubric,
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235], textColor: 255 },
            styles: { fontSize: 11, cellPadding: 5 },
        });
    } else {
        doc.setFontSize(11);
        doc.setTextColor(150, 150, 150);
        doc.text("Project has not been evaluated yet.", 14, doc.lastAutoTable.finalY + 25);
    }

    // -- Footer --
    const yPos = doc.lastAutoTable.finalY + 40;

    doc.setDrawColor(150);
    doc.line(14, yPos, 80, yPos); // Signature Line
    doc.setFontSize(10);
    doc.setTextColor(50);
    doc.text("Mentor Signature", 14, yPos + 5);

    doc.line(pageWidth - 84, yPos, pageWidth - 14, yPos); // Stamp Line
    doc.text("Institution Stamp", pageWidth - 84, yPos + 5);

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by AuditX on ${new Date().toLocaleDateString()}`, pageWidth / 2, 280, { align: 'center' });

    // Save
    doc.save(`${project.teamName}_Report.pdf`);
};
